name: Release to dev
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    uses: cere-io/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:18-buster'
      install_packages_command: 'cp .env.dev .env; npm ci --legacy-peer-deps'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'dist'
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      s3_bucket_name: 'funnel.bullish.dev.cere.io'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
